site_name: EdgeNet Library
nav:
- {"主页": "index.md"}
- {"ECOA 用户隐私政策": "ecoa-policy.md"}
- {"SDVX VI 20230425": "sdvx-6-20230425.md"}
theme:
  name: material
  logo: assets/images/logo.png
extra:
  homepage: https://www.edgenet.ltd/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
  - pymdownx.emoji:  # 表情
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true
copyright: Copyright &copy; 2023 EdgeNet